#!/usr/bin/env bash
# Start the Sysible Controller as a CONTAINER: the controller API (:9000) + the
# web console (:8800) in one container (SQLite in a persistent volume), built from
# the CURRENT checkout so it always runs the code you have.
#
#   sudo ./start-container.sh                 # auto-detect this host's LAN IP
#   sudo ./start-container.sh 192.168.8.249   # or pin the address agents reach
#
# Re-run any time to rebuild and roll the container to your latest code — this is
# the fix for "I updated the code but the old container still serves old routes":
# `--build` bakes the current source into a fresh image every run.
#
# The chosen address is kept in ./.env (git-ignored) so restarts reuse it. The
# DB, TLS cert, API key and cookie secret live in the `sysible-data` volume and
# persist across rebuilds on their own.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE="$HERE/docker-compose.yml"
ENV_FILE="$HERE/.env"

# docker compose v2 (plugin) or v1 (standalone)?
if docker compose version >/dev/null 2>&1; then DC=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then DC=(docker-compose)
else echo "ERROR: docker compose not found — install Docker + the compose plugin." >&2; exit 1; fi

# The address AGENTS actually reach this controller at (host LAN IP or DNS). In a
# container the controller otherwise advertises its docker-bridge IP (172.x), so
# agent bundles strand the fleet on an unreachable address. REQUIRED.
# Precedence: arg > env > auto-detect the default-route source IP.
ADDR="${1:-${SYSIBLE_CONTROLLER_ADDR:-}}"
if [[ -z "$ADDR" ]]; then
  ADDR="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
fi
if [[ -z "$ADDR" ]]; then
  echo "ERROR: couldn't auto-detect this host's LAN IP. Pass it explicitly:" >&2
  echo "   sudo $0 <lan-ip-or-dns>" >&2
  exit 1
fi

# A standalone (systemd) controller would fight this container for :9000/:8800.
# Since you're running everything as containers, stop it first.
if command -v systemctl >/dev/null 2>&1; then
  for svc in sysible-backend sysible-webgui; do
    if systemctl is-active --quiet "$svc" 2>/dev/null; then
      echo "WARNING: standalone service '$svc' is running and will collide with the" >&2
      echo "         container on its port. Stop it before continuing:" >&2
      echo "             sudo systemctl disable --now $svc" >&2
    fi
  done
fi

# Persist the chosen address so restarts reuse it. Both vars point at the same
# address: _ADDR is baked into agent bundles, _HOSTNAMES into the TLS cert SANs.
( umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by start-container.sh on $(date -Is 2>/dev/null || date).
SYSIBLE_CONTROLLER_ADDR=$ADDR
SYSIBLE_CONTROLLER_HOSTNAMES=$ADDR,localhost
EOF
)
echo "Wrote $ENV_FILE (controller address $ADDR)."

echo "Building image from the current checkout and starting the container..."
"${DC[@]}" -f "$COMPOSE" --env-file "$ENV_FILE" up -d --build

echo
echo "== Sysible Controller (container) =="
"${DC[@]}" -f "$COMPOSE" ps || true
cat <<EOF

Web console : https://$ADDR:8800/    (first run: create your administrator; on an
                                      unattended run the seeded password is printed
                                      once in the logs — ${DC[*]} -f "$COMPOSE" logs -f)
Agent API   : https://$ADDR:9000/    (SLEP and agents connect here)

In SLEP, point the Controller connection at  https://$ADDR:9000  — its self-signed
cert is trusted on first use (TOFU). To let host agents verify the controller,
copy its cert out:

  ${DC[*]} -f "$COMPOSE" cp sysible-controller:/data/certs/server.crt ./server.crt

Re-run this script any time to rebuild + roll the container to your latest code.
EOF
